# ctlptl registry for local Tilt development.
# Create: task registry:up (or task r:up)
# Delete: task registry:down (or task r:d)
apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: ctlptl-registry
port: 5005
