apiVersion: v1
kind: ServiceAccount
metadata:
  name: rmapi
  namespace: opendefence-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rmapi
rules:
  - apiGroups: ["platform.opendefence.fi"]
    resources: ["users"]
    verbs: ["get", "list", "create"]
  - apiGroups: ["platform.opendefence.fi"]
    resources: ["invites"]
    verbs: ["get", "list", "create"]
  - apiGroups: ["platform.opendefence.fi"]
    resources: ["invites/status"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rmapi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rmapi
subjects:
  - kind: ServiceAccount
    name: rmapi
    namespace: opendefence-system
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rmapi-jwt
  namespace: opendefence-system
spec:
  secretName: rmapi-jwt  # pragma: allowlist secret
  commonName: rmapi-jwt
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - digital signature
  issuerRef:
    name: operator-ca
    kind: Issuer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmapi
  namespace: opendefence-system
  labels:
    app: rmapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmapi
  template:
    metadata:
      labels:
        app: rmapi
    spec:
      serviceAccountName: rmapi
      containers:
        - name: rmapi
          image: rmk8soperator
          args: ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]
          env:
            - name: RMAPI_DNS
              value: localmaeher.dev.pvarki.fi
            - name: RMAPI_JWT_KEY_PATH
              value: /data/persistent/private/jwt.key
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: jwt
              mountPath: /data/persistent/private/jwt.key
              subPath: tls.key
              readOnly: true
      volumes:
        - name: jwt
          secret:
            secretName: rmapi-jwt  # pragma: allowlist secret
---
apiVersion: v1
kind: Service
metadata:
  name: rmapi
  namespace: opendefence-system
spec:
  selector:
    app: rmapi
  ports:
    - name: http
      port: 8000
      targetPort: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rmapi
  namespace: opendefence-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`localmaeher.dev.pvarki.fi`) && PathPrefix(`/api`)
      priority: 200
      services:
        - name: rmapi
          port: 8000
    - kind: Rule
      match: Host(`mtls.localmaeher.dev.pvarki.fi`) && PathPrefix(`/api`)
      priority: 200
      services:
        - name: rmapi
          port: 8000
  tls: {}
